adb shell pm block jp.co.optim.oru
adb shell pm block jp.co.optim.oru.activity.MainControllerActivity
adb shell pm block jp.gamegift
adb shell pm block jp.gamegift.activity.HomeActivity
adb shell pm block com.google.android.videos
adb shell pm block com.google.android.youtube.videos.EntryPoint
adb shell pm block com.kddi.cs.app001
adb shell pm block com.kddi.cs.app001.Agreement
adb shell pm block com.kddi.android.imp
adb shell pm block com.kddi.android.imp.activity.IMPLibraryGroup
adb shell pm block com.google.android.onetimeinitializer
adb shell pm block com.gemalto.tsmproxy
adb shell pm block com.google.android.partnersetup
adb shell pm block com.kddi.disasterapp
adb shell pm block com.kddi.disasterapp.activity.ActivityTopScreen
adb shell pm block com.kddi.android.aucloudlivewallpaper
adb shell pm block com.google.android.gsf.login
adb shell pm block com.kddi.android.easysettingwizard
adb shell pm block com.kddi.android.easysettingwizard.ui.InformationActivity
adb shell pm block com.mobisystems.office
adb shell pm block com.mobisystems.office.splashScreen.SplashScreenActivity
adb shell pm block com.google.android.feedback
adb shell pm block com.google.android.talk
adb shell pm block com.google.android.talk.SigningInActivity
adb shell pm block com.kddi.android.auoneidsetting
adb shell pm block com.kddi.android.auoneidsetting.AuoneidSetting
adb shell pm block com.felicanetworks.mfm
adb shell pm block com.felicanetworks.mfm.ServiceListActivity
adb shell pm block com.google.android.configupdater
adb shell pm block ait.com.vn.main.plus.lte
adb shell pm block ait.com.vn.main.plus.lte.GloballPassportLTEMainActivity
adb shell pm block jp.kyocera.kcmushroom
adb shell pm block com.kddi.android.cmail
adb shell pm block com.kddi.android.cmail.ui.list.ThreadListActivity
adb shell pm block com.felicanetworks.mfs
adb shell pm block com.google.android.gms
adb shell pm block com.google.android.gms.app.settings.GoogleSettingsActivity
adb shell pm block com.kddi.android.screenshotshare
adb shell pm block com.kddi.android.screenshotshare.SettingActivity
adb shell pm block com.kddi.auoneshopping
adb shell pm block com.kddi.auoneshopping.activity.InitializedActivity
adb shell pm block com.threelm.dm.app.kddi
adb shell pm block com.threelm.dm.app.kddi.DeviceManager
adb shell pm block com.google.android.setupwizard
adb shell pm block com.google.android.keep
adb shell pm block com.google.android.keep.activities.BrowseActivity
adb shell pm block com.google.android.syncadapters.calendar
adb shell pm block com.kddi.android.lismobookstore
adb shell pm block com.kddi.android.lismobookstore.library.Bookshelf
adb shell pm block com.kddi.android.aumanagementsystem
adb shell pm block com.google.android.street
adb shell pm block com.kddi.android.ausdbackup
adb shell pm block com.kddi.android.ausdbackup.MainActivity
adb shell pm block com.google.android.googlequicksearchbox
adb shell pm block com.google.android.googlequicksearchbox.VoiceSearchActivity
adb shell pm block com.google.android.apps.plus
adb shell pm block com.google.android.apps.plus.phone.HomeActivity
adb shell pm block com.facebook.katana
adb shell pm block com.facebook.katana.LoginActivity
adb shell pm block jp.kyocera.magu.manual
adb shell pm block jp.kyocera.magu.manual.SearchActivity
adb shell pm block com.android.vending
adb shell pm block com.android.vending.AssetBrowserActivity
adb shell pm block com.google.android.play.games
adb shell pm block com.google.android.gms.games.ui.destination.main.MainActivity
adb shell pm block com.kddi.android.au_wifi_connect
adb shell pm block jp.co.netvision.WifiConnect.WifiConnectManual
adb shell pm block jp.auone.wallet
adb shell pm block jp.auone.wallet.activity.AppStartActivity
adb shell pm block com.google.android.music
adb shell pm block com.android.music.activitymanagement.TopLevelActivity
adb shell pm block com.kddi.pass.launcher
adb shell pm block com.kddi.pass.launcher.Launch
adb shell pm block com.felicanetworks.mfw.a.boot
adb shell pm block com.google.android.gm
adb shell pm block com.google.android.gm.ConversationListActivityGmail
adb shell pm block com.google.android.backuptransport
adb shell pm block com.kddi.android.UtaPass
adb shell pm block com.kddi.android.UtaPass.HomeActivity
adb shell pm block jp.kyocera.sitek
adb shell pm block jp.kyocera.sitek.SiteKActivity
adb shell pm block com.kddi.market
adb shell pm block com.kddi.market.activity.ActivityMain
adb shell pm block com.kddi.android.btdun
adb shell pm block jp.kyocera.kyocerahome.launcher
adb shell pm block com.kyocera.weatherclock
adb shell pm block com.google.android.apps.maps
adb shell pm block com.google.android.maps.MapsActivity
adb shell pm block com.google.android.youtube
adb shell pm block com.google.android.youtube.app.honeycomb.Shell$HomeActivity
adb shell pm block com.google.android.apps.cloudprint
adb shell pm block com.kddi.android.auclouduploader
adb shell pm block com.kddi.android.auclouduploader.activity.StartupActivity
adb shell pm block com.kddi.android.email
adb shell pm block com.kddi.android.email.system.AppStarter
adb shell pm block jp.iconit.jp_barcodereader
adb shell pm block jp.iconit.jp_barcodereader.activity.BootActivity
adb shell pm block jp.gree.android.pf.greeapp1753
adb shell pm block jp.gree.android.pf.greeapp1753.MainActivity
adb shell pm block com.google.android.gsf
adb shell pm block com.svox.pico
adb shell pm block com.kddi.android.emailprov
adb shell pm block com.android.facelock
adb shell pm block com.gunosy.au
adb shell pm block com.gunosy.android.activity.MainActivity
adb shell pm block com.android.chrome
adb shell pm block com.google.android.apps.chrome.Main
adb shell pm block jibe.android.activity
adb shell pm block jibe.android.activity.LoginActivity
adb shell pm block com.google.android.apps.docs
adb shell pm block com.google.android.apps.docs.app.NewMainProxyActivity
adb shell pm block com.kddi.ux.station
adb shell pm block com.google.android.syncadapters.contacts
adb shell pm block com.google.android.apps.books
adb shell pm block com.google.android.apps.books.app.BooksActivity
