adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop04
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomosimplehome
adb shell pm uninstall -k --user 0 com.nttdocomo.android.store
adb shell pm uninstall -k --user 0 com.nttdocomo.android.store.WebActivity
adb shell pm uninstall -k --user 0 com.nextbit.app
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dhome
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dhome.mag.MagLaunchActivity
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.android.youtube.app.honeycomb.Shell$HomeActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.bugreport
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.google.android.music.tombstone.LauncherActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.iconcier_contents
adb shell pm uninstall -k --user 0 com.nttdocomo.android.socialphonebook
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.saigaiban
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.saigaiban.activity.InitEulaViewerActivity
adb shell pm uninstall -k --user 0 com.google.android.launcher
adb shell pm uninstall -k --user 0 com.google.android.launcher.StubApp
adb shell pm uninstall -k --user 0 com.google.android.apps.cloudprint
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox.SearchActivity
adb shell pm uninstall -k --user 0 com.google.android.talk
adb shell pm uninstall -k --user 0 com.google.android.talk.SigningInActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.voiceeditor
adb shell pm uninstall -k --user 0 jp.co.sharp.android.lifekit
adb shell pm uninstall -k --user 0 jp.co.sharp.android.lifekit.LifekitActivity
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.carriermail
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.carriermail.activity.EulaViewer
adb shell pm uninstall -k --user 0 com.google.android.setupwizard
adb shell pm uninstall -k --user 0 com.android.chrome
adb shell pm uninstall -k --user 0 com.google.android.apps.chrome.Main
adb shell pm uninstall -k --user 0 jp.co.canon.android.printservice.plugin
adb shell pm uninstall -k --user 0 jp.co.canon.android.printservice.plugin.WalkThroughActivity
adb shell pm uninstall -k --user 0 com.google.android.play.games
adb shell pm uninstall -k --user 0 com.google.android.gms.games.ui.destination.main.MainActivity
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.nttdocomo.android.idmanager
adb shell pm uninstall -k --user 0 com.google.android.calendar
adb shell pm uninstall -k --user 0 com.android.calendar.AllInOneActivity
adb shell pm uninstall -k --user 0 com.google.android.inputmethod.latin
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop03
adb shell pm uninstall -k --user 0 com.nttdocomo.android.schedulememo
adb shell pm uninstall -k --user 0 com.nttdocomo.android.schedulememo.ScheduleMemoActivity
adb shell pm uninstall -k --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall -k --user 0 com.nttdocomo.android.sdcardbackup
adb shell pm uninstall -k --user 0 com.nttdocomo.android.sdcardbackup.view.LaunchActivity
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.lcsappsub
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.lcsapp
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.youtube.videos.EntryPoint
adb shell pm uninstall -k --user 0 com.nttdocomo.android.settings.lac
adb shell pm uninstall -k --user 0 sharp.jp.android.makersiteappli
adb shell pm uninstall -k --user 0 sharp.jp.android.makersiteappli.activity.Launcher
adb shell pm uninstall -k --user 0 com.google.android.syncadapters.contacts
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.apps.photos.home.HomeActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.areamail
adb shell pm uninstall -k --user 0 com.google.android.gms
adb shell pm uninstall -k --user 0 com.google.android.gms.app.settings.GoogleSettingsActivity
adb shell pm uninstall -k --user 0 com.google.android.backuptransport
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomo_market
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomo_market.Docomo_market
adb shell pm uninstall -k --user 0 com.google.android.apps.maps
adb shell pm uninstall -k --user 0 com.google.android.maps.MapsActivity
adb shell pm uninstall -k --user 0 jp.co.sharp.android.shinstructionmanual04ge
adb shell pm uninstall -k --user 0 jp.co.sharp.android.shinstructionmanual04ge.InstructionManualActivity
adb shell pm uninstall -k --user 0 com.android.contacts
adb shell pm uninstall -k --user 0 com.android.contacts.activities.PeopleActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.remotelock
adb shell pm uninstall -k --user 0 com.nttdocomo.android.accountauthenticator
adb shell pm uninstall -k --user 0 com.google.android.GoogleCamera
adb shell pm uninstall -k --user 0 com.android.camera.CameraLauncher
adb shell pm uninstall -k --user 0 com.nttdocomo.android.cloudset
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.app.NewMainProxyActivity
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.natural03
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop05
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dcmvoicerecognition
adb shell pm uninstall -k --user 0 com.nttdocomo.android.wipe
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mediaplayer
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mediaplayer.MediaPlayerActivity
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.natural02
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feeluxhome
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop01
adb shell pm uninstall -k --user 0 com.google.android.apps.books
adb shell pm uninstall -k --user 0 com.google.android.apps.books.app.BooksActivity
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.gm.ConversationListActivityGmail
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop02
adb shell pm uninstall -k --user 0 com.nttdocomo.android.databackup
adb shell pm uninstall -k --user 0 com.android.vending
adb shell pm uninstall -k --user 0 com.android.vending.AssetBrowserActivity
adb shell pm uninstall -k --user 0 com.google.android.apps.plus
adb shell pm uninstall -k --user 0 com.google.android.apps.plus.phone.HomeActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.atf
adb shell pm uninstall -k --user 0 com.google.android.gsf
adb shell pm uninstall -k --user 0 com.google.android.partnersetup
adb shell pm uninstall -k --user 0 com.google.android.gsf.login
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.natural01
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop04
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomosimplehome
adb shell pm uninstall -k --user 0 com.nttdocomo.android.store
adb shell pm uninstall -k --user 0 com.nttdocomo.android.store.WebActivity
adb shell pm uninstall -k --user 0 com.nextbit.app
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dhome
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dhome.mag.MagLaunchActivity
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.android.youtube.app.honeycomb.Shell$HomeActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.bugreport
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.google.android.music.tombstone.LauncherActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.iconcier_contents
adb shell pm uninstall -k --user 0 com.nttdocomo.android.socialphonebook
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.saigaiban
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.saigaiban.activity.InitEulaViewerActivity
adb shell pm uninstall -k --user 0 com.google.android.launcher
adb shell pm uninstall -k --user 0 com.google.android.launcher.StubApp
adb shell pm uninstall -k --user 0 com.google.android.apps.cloudprint
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox.SearchActivity
adb shell pm uninstall -k --user 0 com.google.android.talk
adb shell pm uninstall -k --user 0 com.google.android.talk.SigningInActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.voiceeditor
adb shell pm uninstall -k --user 0 jp.co.sharp.android.lifekit
adb shell pm uninstall -k --user 0 jp.co.sharp.android.lifekit.LifekitActivity
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.carriermail
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.carriermail.activity.EulaViewer
adb shell pm uninstall -k --user 0 com.google.android.setupwizard
adb shell pm uninstall -k --user 0 com.android.chrome
adb shell pm uninstall -k --user 0 com.google.android.apps.chrome.Main
adb shell pm uninstall -k --user 0 jp.co.canon.android.printservice.plugin
adb shell pm uninstall -k --user 0 jp.co.canon.android.printservice.plugin.WalkThroughActivity
adb shell pm uninstall -k --user 0 com.google.android.play.games
adb shell pm uninstall -k --user 0 com.google.android.gms.games.ui.destination.main.MainActivity
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.nttdocomo.android.idmanager
adb shell pm uninstall -k --user 0 com.google.android.calendar
adb shell pm uninstall -k --user 0 com.android.calendar.AllInOneActivity
adb shell pm uninstall -k --user 0 com.google.android.inputmethod.latin
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop03
adb shell pm uninstall -k --user 0 com.nttdocomo.android.schedulememo
adb shell pm uninstall -k --user 0 com.nttdocomo.android.schedulememo.ScheduleMemoActivity
adb shell pm uninstall -k --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall -k --user 0 com.nttdocomo.android.sdcardbackup
adb shell pm uninstall -k --user 0 com.nttdocomo.android.sdcardbackup.view.LaunchActivity
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.lcsappsub
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.lcsapp
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.youtube.videos.EntryPoint
adb shell pm uninstall -k --user 0 com.nttdocomo.android.settings.lac
adb shell pm uninstall -k --user 0 sharp.jp.android.makersiteappli
adb shell pm uninstall -k --user 0 sharp.jp.android.makersiteappli.activity.Launcher
adb shell pm uninstall -k --user 0 com.google.android.syncadapters.contacts
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.apps.photos.home.HomeActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.areamail
adb shell pm uninstall -k --user 0 com.google.android.gms
adb shell pm uninstall -k --user 0 com.google.android.gms.app.settings.GoogleSettingsActivity
adb shell pm uninstall -k --user 0 com.google.android.backuptransport
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomo_market
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomo_market.Docomo_market
adb shell pm uninstall -k --user 0 com.google.android.apps.maps
adb shell pm uninstall -k --user 0 com.google.android.maps.MapsActivity
adb shell pm uninstall -k --user 0 jp.co.sharp.android.shinstructionmanual04ge
adb shell pm uninstall -k --user 0 jp.co.sharp.android.shinstructionmanual04ge.InstructionManualActivity
adb shell pm uninstall -k --user 0 com.android.contacts
adb shell pm uninstall -k --user 0 com.android.contacts.activities.PeopleActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.remotelock
adb shell pm uninstall -k --user 0 com.nttdocomo.android.accountauthenticator
adb shell pm uninstall -k --user 0 com.google.android.GoogleCamera
adb shell pm uninstall -k --user 0 com.android.camera.CameraLauncher
adb shell pm uninstall -k --user 0 com.nttdocomo.android.cloudset
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.app.NewMainProxyActivity
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.natural03
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop05
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dcmvoicerecognition
adb shell pm uninstall -k --user 0 com.nttdocomo.android.wipe
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mediaplayer
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mediaplayer.MediaPlayerActivity
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.natural02
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feeluxhome
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop01
adb shell pm uninstall -k --user 0 com.google.android.apps.books
adb shell pm uninstall -k --user 0 com.google.android.apps.books.app.BooksActivity
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.gm.ConversationListActivityGmail
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.colorpop02
adb shell pm uninstall -k --user 0 com.nttdocomo.android.databackup
adb shell pm uninstall -k --user 0 com.android.vending
adb shell pm uninstall -k --user 0 com.android.vending.AssetBrowserActivity
adb shell pm uninstall -k --user 0 com.google.android.apps.plus
adb shell pm uninstall -k --user 0 com.google.android.apps.plus.phone.HomeActivity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.atf
adb shell pm uninstall -k --user 0 com.google.android.gsf
adb shell pm uninstall -k --user 0 com.google.android.partnersetup
adb shell pm uninstall -k --user 0 com.google.android.gsf.login
adb shell pm uninstall -k --user 0 jp.co.sharp.android.feelux.theme.natural01